export const ErrorCodes = {
    INTERNAL_SERVER_ERROR: { status: "internal-server-error", code: 500 },
    TOKEN_NOT_FOUND: { status: "token-not-found", code: 401 },
    UNAUTHORIZED: { status: "unauthorized", code: 401 },
    INVALID_EMAIL: { status: "invalid-email", code: 400 },
    WRONG_TYPE: { status: "wrong-type", code: 400 },
    WEAK_PASSWORD: { status: "weak-password", code: 400 },
    EMAIL_ALREADY_IN_USE: { status: "email-already-in-use", code: 409 },
    INVALID_CREDENTIAL: { status: "invalid-credential", code: 401 },
    NOT_FOUND: { status: "not-found", code: 404 },
    INVALID_INPUT: { status: "invalid-input", code: 400 },
    ALREADY_EXISTS: { status: "already-exists", code: 409 },
    MISSING_PARAMETERS: { status: "missing-parameters", code: 400 },
    INVALID_PARAMETERS: { status: "invalid-parameters", code: 400 },
    PAYLOAD_TOO_LARGE: { status: "payload-too-large", code: 413 },
    RATE_LIMIT_EXCEEDED: { status: "rate-limit-exceeded", code: 429 },
    FORBIDDEN: { status: "forbidden", code: 403 },
    RESOURCE_LOCKED: { status: "resource-locked", code: 423 },
    CONFLICT: { status: "conflict", code: 409 },
    SERVICE_UNAVAILABLE: { status: "service-unavailable", code: 503 },
    DATABASE_ERROR: { status: "database-error", code: 500 },
    TIMEOUT: { status: "timeout", code: 504 },
    UNSUPPORTED_OPERATION: { status: "unsupported-operation", code: 400 },
    DUPLICATE_REQUEST: { status: "duplicate-request", code: 409 },
    EXPIRED_TOKEN: { status: "expired-token", code: 401 },
    BAD_GATEWAY: { status: "bad-gateway", code: 502 },
    GONE: { status: "gone", code: 410 },
    LENGTH_REQUIRED: { status: "length-required", code: 411 },
    PRECONDITION_FAILED: { status: "precondition-failed", code: 412 },
    REQUEST_ENTITY_TOO_LARGE: { status: "request-entity-too-large", code: 413 },
    REQUEST_URI_TOO_LONG: { status: "request-uri-too-long", code: 414 },
    UNSUPPORTED_MEDIA_TYPE: { status: "unsupported-media-type", code: 415 },
    RANGE_NOT_SATISFIABLE: { status: "range-not-satisfiable", code: 416 },
    EXPECTATION_FAILED: { status: "expectation-failed", code: 417 },
    UPGRADE_REQUIRED: { status: "upgrade-required", code: 426 },
    TOO_MANY_REQUESTS: { status: "too-many-requests", code: 429 },
    CLIENT_CLOSED_REQUEST: { status: "client-closed-request", code: 499 },
};

export const SuccessCodes = {
    OK: { status: "ok", code: 200 },
    CREATED: { status: "created", code: 201 },
    ACCEPTED: { status: "accepted", code: 202 },
    NO_CONTENT: { status: "no-content", code: 204 },
    RESET_CONTENT: { status: "reset-content", code: 205 },
    PARTIAL_CONTENT: { status: "partial-content", code: 206 },
    MULTI_STATUS: { status: "multi-status", code: 207 },
    ALREADY_REPORTED: { status: "already-reported", code: 208 },
    IM_USED: { status: "im-used", code: 226 },
};
